// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// AuthData defines model for AuthData.
type AuthData struct {
	AccessToken string `json:"access_token"`
	User        User   `json:"user"`
}

// AuthEnvelope defines model for AuthEnvelope.
type AuthEnvelope struct {
	Code int32     `json:"code"`
	Data *AuthData `json:"data,omitempty"`
	Msg  string    `json:"msg"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MeData defines model for MeData.
type MeData struct {
	User User `json:"user"`
}

// MeEnvelope defines model for MeEnvelope.
type MeEnvelope struct {
	Code int32   `json:"code"`
	Data *MeData `json:"data,omitempty"`
	Msg  string  `json:"msg"`
}

// OkEnvelope defines model for OkEnvelope.
type OkEnvelope struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

// PhoneLoginRequest defines model for PhoneLoginRequest.
type PhoneLoginRequest struct {
	Code  string `json:"code"`
	Phone string `json:"phone"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    *string `json:"email,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// SmsCodeRequest defines model for SmsCodeRequest.
type SmsCodeRequest struct {
	Phone string `json:"phone"`
}

// TokenData defines model for TokenData.
type TokenData struct {
	AccessToken string `json:"access_token"`
}

// TokenEnvelope defines model for TokenEnvelope.
type TokenEnvelope struct {
	Code int32      `json:"code"`
	Data *TokenData `json:"data,omitempty"`
	Msg  string     `json:"msg"`
}

// User defines model for User.
type User struct {
	Avatar    *string `json:"avatar,omitempty"`
	CreatedAt int64   `json:"created_at"`
	Email     string  `json:"email"`
	Id        string  `json:"id"`
	Nickname  *string `json:"nickname,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Status    *string `json:"status,omitempty"`
	Username  string  `json:"username"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LoginByPhoneJSONRequestBody defines body for LoginByPhone for application/json ContentType.
type LoginByPhoneJSONRequestBody = PhoneLoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// SendSmsCodeJSONRequestBody defines body for SendSmsCode for application/json ContentType.
type SendSmsCodeJSONRequestBody = SmsCodeRequest
